version: "3.7"
services:
  olive_guide_db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  olive_guide_web:
    build: .
    env_file:
      - ./olive_guide/.env
    ports:
      - 8000:8000
    volumes:
      - .:/olive_guide
    depends_on:
      - olive_guide_db
  olive_guide_nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/static:/var/www/static/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - olive_guide_web
volumes:
  postgres_data:
