version: '3.2'
services:

    db:
        image: mdillon/postgis:10
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    web:
        build: .
        env_file:
            - ./olive_guide/.env
        ports:
            - 8000:8000
        volumes:
            - .:/olive_guide
        depends_on:
            - db
volumes:
  postgres_data:
